esphome:
  name: esp01sAht10Oled
  friendly_name: esp01s Aht10 Oled

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp01sAht10Oled Fallback Hotspot"
    password: ""

captive_portal:

font:
   # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 10
    
i2c:
  sda: 2
  scl: 0
  id: bus_a
  frequency: 200khz

sensor:
  - platform: aht10
    temperature:
      name: "Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      filters:
        - offset: -2.2
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      filters:
        - offset: 7.58
    i2c_id: bus_a
    address: 0x38
    update_interval: 10s
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    #reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print(0, 10, id(roboto), "Hello World!");